# Generated by Django 3.1.4 on 2021-01-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20210106_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_db',
            name='country',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='author_db',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='card_db',
            name='accuracy_date',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='card_db',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='exhibition_db',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='person',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='fund_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=120),
        ),
    ]
