# Generated by Django 3.1.4 on 2021-01-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20210111_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directors',
            old_name='user_id',
            new_name='users_id',
        ),
        migrations.RenameField(
            model_name='fund_manager',
            old_name='user_id',
            new_name='users_id',
        ),
    ]
